// AUTO-GENERATED by scripts/generate-contract-erd.mjs from Backend-Shared-Contract. Do not edit by hand.
export const CONTRACT_ERD_DATA_URL = '/data/contract-erd.json';

export type ContractNodeKind = 'contract' | 'common';
export type ContractFieldKind = 'primitive' | 'enum' | 'contract' | 'common' | 'external';
export type ContractEdgeKind =
  | 'contains'
  | 'embeds'
  | 'references'
  | 'snapshot'
  | 'event'
  | 'polymorphic';

export interface ContractField {
  name: string;
  jsonName: string;
  type: string;
  typeName: string;
  packageName: string;
  kind: ContractFieldKind;
  optional: boolean;
  repeated: boolean;
  embedded: boolean;
  targetId: string;
}

export interface ContractNode {
  id: string;
  packageName: string;
  name: string;
  fullName: string;
  sourcePath: string;
  kind: ContractNodeKind;
  fields: ContractField[];
}

export interface ContractEdge {
  id: string;
  source: string;
  target: string;
  sourceField: string;
  label: string;
  kind: ContractEdgeKind;
  cardinality: string;
}

export interface ContractErdMetadata {
  repoUrl: string;
  ref: string;
  commit: string;
  modulePath: string;
  generatedAt: string;
  nodeCount: number;
  edgeCount: number;
}

export interface ContractErdData {
  metadata: ContractErdMetadata;
  packages: string[];
  nodes: ContractNode[];
  edges: ContractEdge[];
}

export interface ContractErdSummary {
  metadata: ContractErdMetadata;
  packages: string[];
  packageCounts: Record<string, number>;
}

export const contractErdSummary: ContractErdSummary = {
  "metadata": {
    "repoUrl": "https://github.com/Potato-Mart/Backend-Shared-Contract.git",
    "ref": "main",
    "commit": "7cabf34890709a8ae3402db22178bbd4dff43663",
    "modulePath": "github.com/Potato-Mart/Backend-Shared-Contract/v10",
    "generatedAt": "2026-06-30T13:10:49.885Z",
    "nodeCount": 231,
    "edgeCount": 612
  },
  "packages": [
    "analytics",
    "campaign",
    "category",
    "common",
    "customers",
    "identity",
    "marketing",
    "membership",
    "payments",
    "product",
    "promotion",
    "purchase",
    "sales",
    "shared",
    "shipping",
    "wallet",
    "warehouse",
    "wholesale"
  ],
  "packageCounts": {
    "analytics": 2,
    "campaign": 2,
    "category": 1,
    "common": 22,
    "customers": 12,
    "identity": 35,
    "marketing": 2,
    "membership": 26,
    "payments": 13,
    "product": 10,
    "promotion": 9,
    "purchase": 5,
    "sales": 17,
    "shared": 16,
    "shipping": 5,
    "wallet": 6,
    "warehouse": 24,
    "wholesale": 24
  }
};
